import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import maps, {historicalRequest} from '../src/maps.js';
import images, {retrieveImages,validateInput} from '../src/images.js';
import {approvedImage,wikimediaCandidate,searchSource,searchBatch,DEFAULT_SOURCES} from '../src/sources.js';
import {validateCapabilityManifestV2,validateSettingsState,validateSettingsSubmission,validateWorkerArtifact} from '../../../scripts/contract-v2.mjs';
const bytes=Uint8Array.from([0xff,0xd8,0xff,0xd9]); // Synthetic bytes; native decoder is covered upstream.
const sha=createHash('sha256').update(bytes).digest('hex');
const candidate=(id='commons-1',title='Synthetic daguerreotype plate')=>({id,title,description:'Synthetic silver plate fixture',attribution:'Synthetic fixture · CC0',license:'CC0',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',sourceUrl:'https://commons.wikimedia.org/?curid=1',imageUrl:'https://upload.wikimedia.org/wikipedia/commons/a/ab/fixture.jpg',source:{kind:'public',endpointId:'commons-upload',path:'/wikipedia/commons/a/ab/fixture.jpg'},provider:'wikimedia'});
function setup(outcomes=['selected']) {
  const controller=new AbortController(), calls=[], saved={}; let round=0,stored=0;
  const host={signal:controller.signal,storage:{state:{async get(k){return saved[k]},async set(k,v){saved[k]=v}}},
    network:{async fetch(id,req){calls.push(['network',id,req]);return {status:200,headers:{'content-type':'image/jpeg'},body:bytes}}},
    media:{async store(asset){stored++;return {attachmentId:'fixture-attachment',bytes:asset.bytes.length}}},
    attachments:{async store(asset){return {attachmentId:'fixture-download',bytes:asset.bytes.length}}},
    vision:{async prepareImages(cs){calls.push(['prepare',cs]);return cs.map(c=>({...c,imageId:`image-${c.id}`,provenance:{kind:'public',source:c.source.path,sha256:sha,thumbnailSha256:sha,width:20,height:20}}))},
      async reviewImages(req){calls.push(['review',req]);const outcome=outcomes[Math.min(round++,outcomes.length-1)], reviewed=outcome!=='vision_unavailable';const selected=outcome==='selected'?[req.candidates[0].id]:[];
        return {reviewId:`receipt-${round}`,status:reviewed?'reviewed':'skipped',outcome,model:{provider:'fixture',model:'synthetic'},round:reviewed?round:0,remainingRounds:reviewed?3-round:3,selected,candidates:req.candidates.map(c=>({...c,inspected:reviewed,relevance:reviewed?(selected.includes(c.id)?0.9:0.1):null,reasoning:reviewed?'Synthetic deterministic review':'',...(reviewed?{thumbnailSha256:sha}:{})}))};}},
  };
  return {host,controller,calls,get stored(){return stored},saved};
}
const search=async(_h,_s,_q,batch)=>({candidates:[candidate(`commons-${batch+1}`)],errors:[]});
for(const [name,outcomes,expected,rounds,mode] of [
  ['relevant image selected',['selected'],'selected',1,'vision'],
  ['all candidates rejected',['no_relevant_candidate'],'no_relevant_candidate',3,'vision'],
  ['text-only model fallback',['vision_unavailable'],'selected',1,'metadata'],
  ['second-batch success',['no_relevant_candidate','selected'],'selected',2,'vision'],
]) test(name,async()=>{const s=setup(outcomes);const result=await retrieveImages(s.host,{query:'daguerreotype',maximum:4},'Find pictures of a daguerreotype',DEFAULT_SOURCES,search);assert.equal(result.outcome,expected);assert.equal(result.rounds.length,rounds);assert.equal(result.mode,mode);assert.equal(result.selected.length,expected==='selected'?1:0);assert.equal(result.selected[0]?.inspected,expected==='selected'?mode==='vision':undefined);assert.ok(s.calls.filter(c=>c[0]==='review').every(c=>c[1].request==='Find pictures of a daguerreotype'));});
test('all sources disabled makes zero calls',async()=>{const s=setup();const r=await retrieveImages(s.host,{query:'plate'},'plate',{wikimedia:false,met:false,aic:false},()=>{throw Error('must not search')});assert.equal(r.outcome,'sources_disabled');assert.equal(s.calls.length,0)});
test('source settings persist, default Wikimedia only, model input cannot override',async()=>{const s=setup(),w=images(s.host);assert.deepEqual(await w.getSettings(),{fields:{wikimedia:{value:true},met:{value:false},aic:{value:false}}});await w.applySettings({fields:{wikimedia:false,aic:true}});assert.equal((await w.getSettings()).fields.aic.value,true);assert.equal((await images(s.host).getSettings()).fields.wikimedia.value,false);await assert.rejects(w.applySettings({fields:{evil:true}}));assert.throws(()=>validateInput({query:'plate',sources:['met']}));});
test('invalid maxima and private/raw URL fields rejected',()=>{for(const input of [{query:'x'},{query:'plate',maximum:0},{query:'plate',maximum:6},{query:'plate',path:'/private/photo'},{query:'plate',url:'http://localhost'}])assert.throws(()=>validateInput(input))});
test('no metadata match is allowed to remain empty',async()=>{const s=setup(['vision_unavailable']);const r=await retrieveImages(s.host,{query:'telescope'},'Find a telescope',DEFAULT_SOURCES,search);assert.equal(r.outcome,'no_relevant_candidate');assert.equal(r.selected.length,0);assert.equal(r.rounds.length,1)});
test('cancellation stops before search and after preparation',async()=>{const s=setup();s.controller.abort();await assert.rejects(retrieveImages(s.host,{query:'plate'},'plate',DEFAULT_SOURCES,search),/abort/i);const x=setup();x.host.vision.prepareImages=async()=>{x.controller.abort();return []};await assert.rejects(retrieveImages(x.host,{query:'plate'},'plate',DEFAULT_SOURCES,search),/abort/i);assert.equal(x.stored,0)});
test('forged receipt and wrong thumbnail cannot produce a selected image',async()=>{for(const tamper of [r=>r.selected=['invented'],r=>r.candidates[0].thumbnailSha256='0'.repeat(64),r=>r.candidates[0].imageId='other']){const s=setup(),review=s.host.vision.reviewImages;s.host.vision.reviewImages=async req=>{const r=await review(req);tamper(r);return r};const r=await retrieveImages(s.host,{query:'plate'},'plate',DEFAULT_SOURCES,search);assert.equal(r.outcome,'review_failed');assert.equal(s.stored,0)}});
test('changed image bytes do not inherit an earlier visual review',async()=>{const s=setup();s.host.network.fetch=async()=>({status:200,headers:{'content-type':'image/jpeg'},body:Uint8Array.from([1,2,3])});const r=await retrieveImages(s.host,{query:'plate'},'plate',DEFAULT_SOURCES,search);assert.equal(r.outcome,'media_unavailable');assert.equal(s.stored,0)});
test('duplicate candidates are never reviewed repeatedly',async()=>{const s=setup(['no_relevant_candidate']);const r=await retrieveImages(s.host,{query:'plate'},'plate',DEFAULT_SOURCES,async()=>({candidates:[candidate()],errors:[]}));assert.equal(r.rounds.length,1)});
const page=(license='CC BY 4.0')=>({pageid:1,title:'File:Synthetic plate.jpg',imageinfo:[{thumburl:candidate().imageUrl,extmetadata:{LicenseShortName:{value:license},LicenseUrl:{value:'https://creativecommons.org/licenses/by/4.0/'},Artist:{value:'Synthetic fixture'},Credit:{value:'Synthetic research sample'}}}]});
test('Wikimedia licensing, credits and approved hosts fail closed',()=>{assert.equal(wikimediaCandidate(page()).license,'CC BY 4.0');for(const l of ['Fair use','CC BY-NC 4.0','GFDL','Unknown'])assert.equal(wikimediaCandidate(page(l)),null);const bad=page();delete bad.imageinfo[0].extmetadata.Artist;assert.equal(wikimediaCandidate(bad),null);const mismatch=page();mismatch.imageinfo[0].extmetadata.LicenseUrl.value='https://evil.invalid';assert.equal(wikimediaCandidate(mismatch),null);for(const url of ['http://upload.wikimedia.org/wikipedia/commons/a.jpg','https://upload.wikimedia.org.evil.invalid/wikipedia/commons/a.jpg','https://localhost/x','https://user:pass@upload.wikimedia.org/wikipedia/commons/x','https://upload.wikimedia.org/wikipedia/commons/%2fprivate'])assert.throws(()=>approvedImage(url))});
const jsonResponse=value=>({status:200,headers:{'content-type':'application/json'},body:new TextEncoder().encode(JSON.stringify(value))});
test('search calls only checked sources and never exceeds five candidate slots',async()=>{const calls=[];const host={signal:new AbortController().signal,network:{async fetch(id,r){calls.push([id,r.path]);return jsonResponse(id==='commons'?{query:{pages:{1:page('Public domain')}}}:{data:[]})}}};await searchBatch(host,{wikimedia:true,met:false,aic:false},'plate',0);assert.deepEqual(calls.map(c=>c[0]),['commons']);assert.match(calls[0][1],/^\/w\/api.php\?/);assert.match(calls[0][1],/gsrlimit=5/);calls.length=0;await searchBatch(host,{wikimedia:false,met:false,aic:true},'plate',0);assert.deepEqual(calls.map(c=>c[0]),['aic']);assert.equal(JSON.parse(new URL(calls[0][1],'https://api.artic.edu').searchParams.get('params')).query.term.is_public_domain,true)});
test('museum records require explicit public-domain flags and fixed image origin',async()=>{const item={id:123,title:'Synthetic plate',image_id:'12345678-1234-1234-1234-123456789012',is_public_domain:false};const h={signal:new AbortController().signal,network:{async fetch(){return jsonResponse({data:[item]})}}};assert.equal((await searchSource(h,'aic','plate',0,5)).length,0);item.is_public_domain=true;assert.equal((await searchSource(h,'aic','plate',0,5))[0].license,'CC0');const seen=[];const m={...h,network:{async fetch(_id,r){seen.push(r.path);return jsonResponse(r.path.includes('/search?')?{objectIDs:[1]}:{objectID:1,title:'Synthetic plate',isPublicDomain:true,primaryImageSmall:'https://images.metmuseum.org/CRDImages/ad/fixture.jpg'})}}};assert.equal((await searchSource(m,'met','plate',1,2)).length,1);assert.match(seen[0],/v1\.1\/search\?/);assert.match(seen[0],/offset=2/)});
const source={label:'Synthetic historical fixture',attribution:'Synthetic geometry; not real borders',license:'CC0',url:'https://example.org/synthetic',period:{from:'1800-01-01',to:'1899-12-31'}};
const request={title:'Synthetic historical route',alt:'Synthetic route between two supplied coordinates',markers:[{coordinates:[0,0],label:'A'},{coordinates:[1,1],label:'B'}],routes:[{coordinates:[[0,0],[1,1]],arrow:true}],overlaySource:source};
test('historical runtime enforces evidence, dates and no modern substitution',()=>{assert.deepEqual(historicalRequest({...request,period:{from:'1850-01-01',to:'1850-12-31'}}),request);for(const bad of [{...request},{...request,period:{from:'1750-01-01',to:'1750-12-31'}},{...request,period:source.period,overlaySource:{...source,url:undefined}},{...request,period:source.period,layers:[{query:{provider:'natural-earth'}}]}])assert.throws(()=>historicalRequest(bad));assert.doesNotThrow(()=>historicalRequest({...request,period:{from:'-000500-01-01',to:'-000499-12-31'},overlaySource:{...source,period:{from:'-000600-01-01',to:'-000400-12-31'}}}))});
test('both map tools invoke the native renderer and preserve editable/provenance exports',async()=>{const s=setup();const calls=[];s.host.maps={async render(r){calls.push(r);return {svg:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M0 0L20 20"/></svg>',geometry:[],provenance:{sources:[source]}}}};const w=maps(s.host);for(const toolId of ['render-map','render-historical-map']){const result=await w.invoke({toolId,input:{...request,...(toolId.includes('historical')?{period:source.period}:{})}});assert.equal(result.artifacts[0].view.nodes.filter(n=>n.kind==='download').length,2);assert.equal(result.artifacts[0].data.svg.includes('<svg'),true)}assert.equal(calls.length,2);await assert.rejects(w.invoke({toolId:'invented',input:request}));});
test('manifest settings and paid review contract validate',async()=>{const manifest=validateCapabilityManifestV2(JSON.parse(fs.readFileSync(fileURLToPath(new URL('../capabilities/images/capability.json',import.meta.url)))));assert.equal(manifest.tools[0].billing,'per-call');assert.equal(manifest.permissions.model,undefined);assert.equal(manifest.permissions.vision.maxRounds,3);const w=images(setup().host);validateSettingsState(await w.getSettings(),manifest.settings);assert.throws(()=>validateSettingsSubmission({fields:{met:'yes'}},manifest.settings));});
