// Curated vocabulary, never populated by runtime translation. Keys are canonical registry ids.
// These aliases are exact unless the existing English registry marks a region match generalised.
export const SPANISH = {
  deltoid: ['Deltoides', 'deltoides'], biceps: ['Bíceps braquial', 'bíceps', 'bíceps braquial'],
  triceps: ['Tríceps braquial', 'tríceps', 'tríceps braquial'], trapezius: ['Trapecio', 'trapecio'],
  'rectus-abdominis': ['Recto abdominal', 'recto abdominal'], 'tibialis-anterior': ['Tibial anterior', 'tibial anterior'],
  kidneys: ['Riñones', 'riñón', 'riñones'], liver: ['Hígado', 'hígado'], heart: ['Corazón', 'corazón'],
  lungs: ['Pulmones', 'pulmón', 'pulmones'], brain: ['Cerebro', 'cerebro'], stomach: ['Estómago', 'estómago'],
  pancreas: ['Páncreas', 'páncreas'], spleen: ['Bazo', 'bazo'], gallbladder: ['Vesícula biliar', 'vesícula biliar'],
  'small-intestine': ['Intestino delgado', 'intestino delgado'], colon: ['Colon', 'colon'], rectum: ['Recto', 'recto'],
  appendix: ['Apéndice', 'apéndice'], 'urinary-bladder': ['Vejiga urinaria', 'vejiga', 'vejiga urinaria'],
  esophagus: ['Esófago', 'esófago'], 'thyroid-gland': ['Glándula tiroides', 'tiroides', 'glándula tiroides'],
  'adrenal-glands': ['Glándulas suprarrenales', 'glándulas suprarrenales', 'suprarrenales'],
  'spinal-cord': ['Médula espinal', 'médula espinal'], tongue: ['Lengua', 'lengua'],
  'pituitary-gland': ['Hipófisis', 'hipófisis'], eyes: ['Ojos', 'ojo', 'ojos'], breasts: ['Mamas', 'mamas'],
  'prostate-gland': ['Próstata', 'próstata'], testes: ['Testículos', 'testículo', 'testículos'],
  epididymis: ['Epidídimo', 'epidídimo'], uterus: ['Útero', 'útero'], ovaries: ['Ovarios', 'ovario', 'ovarios'],
  vagina: ['Vagina', 'vagina'], 'fallopian-tubes': ['Trompas uterinas', 'trompas uterinas', 'trompas de falopio'],
  'uterine-cervix': ['Cuello uterino', 'cuello uterino'], placenta: ['Placenta', 'placenta'],
  endometrium: ['Endometrio', 'endometrio'], diaphragm: ['Diafragma', 'diafragma'], aorta: ['Aorta', 'aorta'],
  cerebellum: ['Cerebelo', 'cerebelo'], hippocampus: ['Hipocampo', 'hipocampo'],
  'cerebral-cortex': ['Corteza cerebral', 'corteza cerebral'], thalamus: ['Tálamo', 'tálamo'],
  hypothalamus: ['Hipotálamo', 'hipotálamo'], 'oral-cavity': ['Cavidad oral', 'cavidad oral'], nose: ['Nariz', 'nariz'],
  head: ['Cabeza', 'cabeza'], neck: ['Región cervical', 'cuello', 'región cervical'],
  hands: ['Manos', 'mano', 'manos'], feet: ['Pies', 'pie', 'pies'], knees: ['Rodillas', 'rodilla', 'rodillas'],
  ankles: ['Tobillos', 'tobillo', 'tobillos'], hair: ['Cabello', 'cabello'],
};
export const SPANISH_FMA = {
  FMA7203: ['Riñones', 'riñón', 'riñones'], FMA7204: ['Riñón derecho', 'riñón derecho'], FMA7205: ['Riñón izquierdo', 'riñón izquierdo'],
  FMA7197: ['Hígado', 'hígado'], FMA9600: ['Próstata', 'próstata'], FMA7210: ['Testículos', 'testículos', 'testículo'],
  FMA9611: ['Fémur', 'fémur', 'fémures'], FMA13303: ['Húmero', 'húmero'], FMA24476: ['Tibia', 'tibia'],
  FMA9629: ['Supraespinoso', 'supraespinoso'], FMA18060: ['Psoas mayor', 'psoas mayor'],
  FMA50863: ['Nervio óptico', 'nervio óptico'], FMA50865: ['Nervio troclear', 'nervio troclear'],
  FMA7152: ['Sistema digestivo', 'sistema digestivo', 'aparato digestivo'],
  FMA7157: ['Sistema nervioso', 'sistema nervioso'], FMA7158: ['Sistema respiratorio', 'sistema respiratorio'],
  FMA7159: ['Sistema urinario', 'sistema urinario', 'aparato urinario'],
  FMA7160: ['Sistema reproductor', 'sistema reproductor', 'aparato reproductor'],
  FMA7161: ['Sistema cardiovascular', 'sistema cardiovascular'],
  FMA23881: ['Sistema esquelético', 'sistema esquelético', 'esqueleto'],
  FMA9668: ['Sistema endocrino', 'sistema endocrino'],
};
