// GENERATED by Nodus scripts/sync-skill-marketplace.mjs; do not edit.

// packages/capability-api/src/limits.ts
var CORE_CAPABILITY_IDS = ["nodus:svg", "nodus:image", "nodus:3d", "nodus:maps", "nodus:vision"];
var RESERVED_CAPABILITY_IDS = ["nodus:chemistry", "nodus:legal", "nodus:genomics"];
var LIMITS = {
  /** Tool timeouts are declared per tool and clamped to this window. */
  toolTimeoutMsMin: 1e3,
  toolTimeoutMsMax: 3e5,
  toolsPerCapability: 24,
  /** Grace period between "please stop" and killing the utility process. */
  cancelGraceMs: 2e3,
  /** Package extraction. A staged archive that exceeds any of these is rejected whole. */
  packageCompressedBytes: 128 * 1024 * 1024,
  packageExpandedBytes: 512 * 1024 * 1024,
  packageEntries: 25e3,
  /** Interactive 3D models. One asset, stored like any other attachment and rendered by
   *  the core viewer; a capability never ships a renderer of its own. */
  modelBytes: 64 * 1024 * 1024,
  modelJsonBytes: 16 * 1024 * 1024,
  modelNodes: 2e5,
  /** Raster images and sound a capability produced. Same rule as a model: the bytes are
   *  stored as an attachment, checked by the core, and drawn or played by the core. */
  imageBytes: 32 * 1024 * 1024,
  imagePixels: 8e7,
  audioBytes: 128 * 1024 * 1024,
  /** Result kinds that are pure data. None of these needs a host service, a permission or
   *  an attachment: a capability returns the values and the core draws them. */
  mathChars: 4e3,
  chartSeries: 12,
  chartPoints: 5e3,
  treeNodes: 2e3,
  treeDepth: 12,
  passageChars: 2e5,
  passageMarks: 5e3,
  comparisonChars: 2e5,
  geoFeatures: 5e3,
  geoPositions: 2e5,
  /** Tiled imagery served over the IIIF Image API. The tiles are fetched by the host,
   *  from an origin the package was already permitted to reach, and never by the page. */
  tileBytes: 8 * 1024 * 1024,
  tilePixels: 4096,
  /** Declarative views. */
  viewNodes: 512,
  viewDepth: 8,
  viewTextChars: 2e4,
  viewSvgChars: 2 * 1024 * 1024,
  viewTableRows: 2e3,
  viewTableColumns: 40,
  /** What a capability may hand back to the model as history. */
  projectionBytes: 500 * 1024,
  artifactSummaryChars: 500,
  /** Chat protocol. */
  chatFenceMaxPerReply: 8,
  chatMutationsPerHook: 64,
  chatPriorityMin: 1,
  chatPriorityMax: 1e3
};

// packages/capability-api/src/identifiers.ts
var NODUS_CAPABILITY_IDS = [...CORE_CAPABILITY_IDS, ...RESERVED_CAPABILITY_IDS];
var LEGACY = {
  svg: "nodus:svg",
  image: "nodus:image",
  "3d": "nodus:3d",
  maps: "nodus:maps",
  vision: "nodus:vision",
  chemistry: "nodus:chemistry",
  legal: "nodus:legal",
  genomics: "nodus:genomics"
};
function normalizeCapabilityId(id) {
  return LEGACY[id] ?? id;
}
var isCoreCapabilityId = (id) => CORE_CAPABILITY_IDS.includes(id);
var isReservedCapabilityId = (id) => RESERVED_CAPABILITY_IDS.includes(id);
var isNodusCapabilityId = (id) => isCoreCapabilityId(id) || isReservedCapabilityId(id);
function isCapabilityReference(value) {
  if (typeof value !== "string" || value.length > 160) return false;
  if (value in LEGACY || isNodusCapabilityId(value)) return true;
  return /^self:[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value) || /^[a-z0-9]+(?:[./-][a-z0-9]+)*:[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value);
}

// packages/capability-api/src/json.ts
var SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
var SEMVER = /^\d+\.\d+\.\d+$/;
var CONTROL = /[\x00-\x08\x0b\x0c\x0e-\x1f]/;
var plainText = (value, max) => typeof value === "string" && value.trim().length > 0 && value.length <= max && !CONTROL.test(value);
var exactKeys = (value, allowed) => Object.keys(value).every((key) => allowed.includes(key));
var SCHEMA_KEYS = ["type", "properties", "required", "items", "enum", "additionalProperties", "minLength", "maxLength", "minItems", "maxItems", "minimum", "maximum"];
function validateJsonSchema(schema, depth = 0) {
  if (!schema || typeof schema !== "object" || Array.isArray(schema) || depth > 8) throw new Error("Invalid capability JSON schema.");
  const value = schema;
  if (!exactKeys(value, SCHEMA_KEYS)) throw new Error("Invalid capability JSON schema.");
  if (value.type && !["null", "boolean", "number", "integer", "string", "array", "object"].includes(value.type)) throw new Error("Invalid capability JSON schema type.");
  if (value.properties) {
    if (value.type !== "object" || Object.keys(value.properties).length > 64) throw new Error("Invalid capability object schema.");
    for (const [key, child] of Object.entries(value.properties)) {
      if (!SLUG.test(key) && !/^[a-z][a-zA-Z0-9]{0,63}$/.test(key) || ["__proto__", "constructor", "prototype"].includes(key)) throw new Error("Invalid capability schema property.");
      validateJsonSchema(child, depth + 1);
    }
  }
  if (value.required && (!Array.isArray(value.required) || value.required.some((key) => typeof key !== "string" || !value.properties?.[key]))) throw new Error("Invalid capability required properties.");
  if (value.items) {
    if (value.type !== "array") throw new Error("Invalid capability array schema.");
    validateJsonSchema(value.items, depth + 1);
  }
  for (const bound of [value.minItems, value.maxItems]) if (bound !== void 0 && (value.type !== "array" || !Number.isInteger(bound) || bound < 0 || bound > 2e5)) throw new Error("Invalid capability array limit.");
  if (value.minItems !== void 0 && value.maxItems !== void 0 && value.minItems > value.maxItems) throw new Error("Invalid capability array limits.");
  if (value.enum && (!Array.isArray(value.enum) || value.enum.length > 100)) throw new Error("Invalid capability enum.");
}
function jsonSchemaMatches(schema, value) {
  if (schema.enum && !schema.enum.some((item) => Object.is(item, value))) return false;
  if (!schema.type) return true;
  if (schema.type === "null") return value === null;
  if (schema.type === "boolean") return typeof value === "boolean";
  if (schema.type === "string") return typeof value === "string" && (schema.minLength === void 0 || value.length >= schema.minLength) && (schema.maxLength === void 0 || value.length <= schema.maxLength);
  if (schema.type === "number" || schema.type === "integer") return typeof value === "number" && Number.isFinite(value) && (schema.type !== "integer" || Number.isInteger(value)) && (schema.minimum === void 0 || value >= schema.minimum) && (schema.maximum === void 0 || value <= schema.maximum);
  if (schema.type === "array") return Array.isArray(value) && (schema.minItems === void 0 || value.length >= schema.minItems) && (schema.maxItems === void 0 || value.length <= schema.maxItems) && (!schema.items || value.every((item) => jsonSchemaMatches(schema.items, item)));
  if (schema.type === "object") {
    if (!value || typeof value !== "object" || Array.isArray(value)) return false;
    const record = value;
    if (schema.required?.some((key) => !(key in record))) return false;
    if (schema.additionalProperties === false && Object.keys(record).some((key) => !schema.properties?.[key])) return false;
    return Object.entries(schema.properties ?? {}).every(([key, child]) => !(key in record) || jsonSchemaMatches(child, record[key]));
  }
  return false;
}
function compareSemver(a, b) {
  const left = a.split(".").map(Number), right = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) if (left[i] !== right[i]) return left[i] - right[i];
  return 0;
}

// packages/capability-api/src/pluginAssets.ts
function validatePluginAssets(input) {
  if (input === void 0) return;
  if (!Array.isArray(input) || input.length > 64) throw new Error("Invalid plugin assets.");
  const ids = /* @__PURE__ */ new Set(), paths = /* @__PURE__ */ new Set();
  let total = 0;
  for (const asset of input) {
    if (!asset || !exactKeys(asset, ["id", "path", "mimeType", "bytes", "sha256"]) || typeof asset.id !== "string" || !SLUG.test(asset.id) || ids.has(asset.id) || typeof asset.path !== "string" || !/^assets\/[a-z0-9]+(?:-[a-z0-9]+)*\.(json|gltf|glb)$/.test(asset.path) || paths.has(asset.path) || !["application/json", "model/gltf+json", "model/gltf-binary"].includes(asset.mimeType) || asset.mimeType === "model/gltf+json" !== asset.path.endsWith(".gltf") || asset.mimeType === "model/gltf-binary" !== asset.path.endsWith(".glb") || !Number.isSafeInteger(asset.bytes) || asset.bytes < 1 || asset.bytes > (asset.mimeType === "model/gltf-binary" ? 64 * 1024 * 1024 : asset.mimeType === "application/json" ? 2e6 : 16 * 1024 * 1024) || typeof asset.sha256 !== "string" || !/^[a-f0-9]{64}$/.test(asset.sha256)) throw new Error("Invalid plugin asset declaration.");
    ids.add(asset.id);
    paths.add(asset.path);
    total += asset.bytes;
  }
  if (total > 128 * 1024 * 1024) throw new Error("Plugin assets exceed 128 MB.");
}
function validatePackagedModelResult(input) {
  const result = input;
  if (!result || !exactKeys(result, ["kind", "panels", "metadata"]) || result.kind !== "model" || !Array.isArray(result.panels) || !result.panels.length || result.panels.length > 12 || JSON.stringify(result).length > 256e3) throw new Error("Invalid packaged model result.");
  for (const panel of result.panels) {
    if (!panel || !exactKeys(panel, ["assetId", "nodeIds", "title", "alt"]) || typeof panel.assetId !== "string" || !SLUG.test(panel.assetId) || !plainText(panel.title, 160) || !plainText(panel.alt, 4e3) || !Array.isArray(panel.nodeIds) || !panel.nodeIds.length || panel.nodeIds.length > 2e3 || panel.nodeIds.some((id) => typeof id !== "string" || !/^[a-zA-Z0-9][a-zA-Z0-9:._-]{0,127}$/.test(id)) || new Set(panel.nodeIds).size !== panel.nodeIds.length) throw new Error("Invalid packaged model panel.");
  }
}

// skill-capabilities/contracts.ts
var CAPABILITY_API_VERSION = 1;
var plain = (value, max) => plainText(value, max);
function validateCapabilityManifest(input) {
  const value = input;
  if (!value || typeof value !== "object" || Array.isArray(value) || !exactKeys(value, ["schemaVersion", "id", "version", "description", "runtime", "entry", "tools", "permissions", "assets"]) || value.schemaVersion !== 1 || !SLUG.test(value.id) || !SEMVER.test(value.version) || !plain(value.description, 500) || value.runtime !== "javascript-sandbox-v1" || value.entry !== "runtime.js" || !Array.isArray(value.tools) || !value.tools.length || value.tools.length > 12 || !value.permissions || typeof value.permissions !== "object" || Array.isArray(value.permissions) || !exactKeys(value.permissions, ["network", "secrets", "storage"])) throw new Error("Invalid capability.json.");
  const ids = /* @__PURE__ */ new Set();
  for (const tool of value.tools) {
    if (!tool || !exactKeys(tool, ["id", "description", "inputSchema", "resultKinds"]) || !SLUG.test(tool.id) || ids.has(tool.id) || !plain(tool.description, 500) || !Array.isArray(tool.resultKinds) || !tool.resultKinds.length || tool.resultKinds.some((kind) => !["text", "json", "table", "svg", "image", "file", "model"].includes(kind))) throw new Error("Invalid capability tool.");
    validateJsonSchema(tool.inputSchema);
    ids.add(tool.id);
  }
  validatePluginAssets(value.assets);
  for (const endpoint of value.permissions.network ?? []) {
    let url;
    try {
      url = new URL(endpoint.origin);
    } catch {
      throw new Error("Invalid capability network origin.");
    }
    if (!SLUG.test(endpoint.id) || url.protocol !== "https:" || url.pathname !== "/" || url.search || url.hash || url.username || url.password || !Array.isArray(endpoint.pathPrefixes) || !endpoint.pathPrefixes.length || endpoint.pathPrefixes.some((prefix) => !prefix.startsWith("/") || prefix.includes("..")) || !Array.isArray(endpoint.methods) || !endpoint.methods.length || endpoint.methods.some((method) => !["GET", "POST", "PUT", "PATCH", "DELETE"].includes(method))) throw new Error("Invalid capability network permission.");
  }
  for (const secret of value.permissions.secrets ?? []) {
    if (!SLUG.test(secret.id) || !plain(secret.label, 80) || typeof secret.required !== "boolean" || !SLUG.test(secret.endpointId) || !/^[A-Za-z0-9-]{1,80}$/.test(secret.header) || secret.prefix !== void 0 && typeof secret.prefix !== "string") throw new Error("Invalid capability secret permission.");
    if (!(value.permissions.network ?? []).some((endpoint) => endpoint.id === secret.endpointId)) throw new Error("Capability secret references an unknown endpoint.");
  }
  if (value.permissions.storage && (!Number.isInteger(value.permissions.storage.maxBytes) || value.permissions.storage.maxBytes < 1024 || value.permissions.storage.maxBytes > 5e6)) throw new Error("Invalid capability storage quota.");
  return structuredClone(value);
}
function validatePluginManifest(input) {
  const value = input;
  if (!value || typeof value !== "object" || Array.isArray(value) || !exactKeys(value, ["schemaVersion", "id", "name", "version", "author", "description", "license", "compatibility", "skills", "capabilities"]) || value.schemaVersion !== 1 || !SLUG.test(value.id) || !plain(value.name, 80) || !SEMVER.test(value.version) || !plain(value.author, 80) || !plain(value.description, 500) || !plain(value.license, 80) || !value.compatibility || value.compatibility.capabilityApi !== CAPABILITY_API_VERSION || !SEMVER.test(value.compatibility.minNodusVersion) || !Array.isArray(value.skills) || !value.skills.length || value.skills.length > 40 || !Array.isArray(value.capabilities) || value.capabilities.length > 20) throw new Error("Invalid plugin.json.");
  const expectedSkills = /* @__PURE__ */ new Set(), expectedCapabilities = /* @__PURE__ */ new Set();
  for (const file of value.skills) {
    const match = /^skills\/([a-z0-9]+(?:-[a-z0-9]+)*)\/skill\.json$/.exec(file);
    if (!match || expectedSkills.has(file)) throw new Error("Invalid plugin skill path.");
    expectedSkills.add(file);
  }
  for (const file of value.capabilities) {
    const match = /^capabilities\/([a-z0-9]+(?:-[a-z0-9]+)*)\/capability\.json$/.exec(file);
    if (!match || expectedCapabilities.has(file)) throw new Error("Invalid plugin capability path.");
    expectedCapabilities.add(file);
  }
  return structuredClone(value);
}

// skill-capabilities/registry/catalog.ts
var BUILTIN_CAPABILITY_REGISTRY = [
  { id: "nodus:vision", version: "1.0.0", description: "Bounded visual relevance review with the selected model.", source: "builtin", tools: [{ id: "review-images", description: "Review host-prepared image candidates; unknown or text-only models skip safely." }] },
  { id: "nodus:maps", version: "1.0.0", description: "Deterministic SVG cartography with approved source retrieval and provenance.", source: "builtin", tools: [{ id: "render", description: "Render geometry, markers and connections as an attributed SVG." }, { id: "retrieve", description: "Retrieve geometry from approved open providers." }] },
  { id: "nodus:svg", version: "1.0.0", description: "Sanitized SVG rendering and quality review.", source: "builtin", tools: [{ id: "render", description: "Render a self-contained SVG." }] },
  { id: "nodus:image", version: "1.0.0", description: "Image generation using the configured provider.", source: "builtin", tools: [{ id: "generate", description: "Generate and persist one image." }] },
  // Deliberately generic: a molecule, a bone, a pot and a building are the same thing to
  // it. Packages hand over a glTF or GLB asset and the core validates, stores and draws
  // it; no discipline is named here and none ever should be.
  { id: "nodus:3d", version: "1.0.0", description: "Validation, storage and interactive viewing of glTF and GLB models.", source: "builtin", tools: [
    { id: "validate", description: "Check that a glTF or GLB asset is self-contained and can be opened." },
    { id: "store", description: "Validate a glTF or GLB asset and keep it beside the conversation for the viewer." }
  ] }
];
var REGISTERED_BUILTIN_CAPABILITY_IDS = BUILTIN_CAPABILITY_REGISTRY.map((entry) => entry.id);

// shared/skillMarketplace.ts
var DEFAULT_SKILL_SOURCE = "https://github.com/NodusResearch/nodus-research-skill-marketplace";
var SKILL_CAPABILITIES = ["svg", "image"];
var SUPPORTED_SKILL_CAPABILITIES = REGISTERED_BUILTIN_CAPABILITY_IDS;
var unsupportedSkillCapabilities = (capabilities) => capabilities.filter((c) => !REGISTERED_BUILTIN_CAPABILITY_IDS.includes(normalizeCapabilityId(c)));
function assertSkillCapabilitiesSupported(capabilities) {
  const invalid = capabilities.filter((capability) => !isCapabilityReference(normalizeCapabilityId(capability)));
  if (invalid.length) throw new Error(`These are not capability identifiers: ${invalid.join(", ")}.`);
}
var skillSlug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 64) || "my-skill";
var slug = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
var plain2 = (value, max) => typeof value === "string" && value.trim().length > 0 && value.length <= max && !/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(value);
function validateManifest(value) {
  const m = value;
  if (!m || typeof m !== "object" || Array.isArray(m) || Object.keys(m).some((k) => !["schemaVersion", "id", "name", "version", "author", "description", "category", "license", "instructions", "capabilities", "tools"].includes(k)) || m.schemaVersion !== 1 || !plain2(m.id, 64) || !slug.test(m.id) || !plain2(m.name, 80) || !plain2(m.description, 500) || !plain2(m.category, 60) || !plain2(m.license, 80) || !plain2(m.author, 39) || !/^[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$/.test(m.author) || !/^\d+\.\d+\.\d+$/.test(m.version) || m.instructions !== "SKILL.md" || !Array.isArray(m.capabilities) || m.capabilities.some((c) => !isCapabilityReference(c)) || new Set(m.capabilities.map(normalizeCapabilityId)).size !== m.capabilities.length || !Array.isArray(m.tools) || m.tools.length > 12) throw new Error("Invalid skill.json: use the Nodus skill package v1 format.");
  const ids = /* @__PURE__ */ new Set();
  for (const tool of m.tools) {
    if (!tool || Object.keys(tool).some((k) => !["id", "description", "entry", "runtime"].includes(k)) || !plain2(tool.id, 64) || !slug.test(tool.id) || ids.has(tool.id) || !plain2(tool.description, 500) || tool.runtime !== "javascript-sandbox" || tool.entry !== `tools/${tool.id}.js`) throw new Error("Invalid tool: use a unique id and tools/<id>.js with javascript-sandbox runtime.");
    ids.add(tool.id);
  }
  return structuredClone(m);
}
function validateSkillPackage(value) {
  const manifest = validateManifest(value?.manifest);
  if (!value.files || typeof value.files !== "object" || Array.isArray(value.files)) throw new Error("Missing skill files.");
  const expected = ["SKILL.md", ...manifest.tools.map((t) => t.entry)];
  if (Object.keys(value.files).some((f) => !expected.includes(f))) throw new Error("Unexpected package file.");
  const files = {};
  for (const file of expected) {
    const source = value.files[file];
    if (!plain2(source, file === "SKILL.md" ? 16e3 : 64e3)) throw new Error(`Missing or oversized ${file}.`);
    files[file] = source;
  }
  return { manifest, files };
}
function normalizeSkillSource(input) {
  const url = new URL(input.trim());
  const match = /^\/([a-zA-Z0-9-]+)\/([a-zA-Z0-9_.-]+)\/?$/.exec(url.pathname);
  if (url.protocol !== "https:" || url.hostname !== "github.com" || url.port || url.username || url.password || url.search || url.hash || !match) throw new Error("Enter a GitHub repository URL: https://github.com/owner/repository");
  const owner = match[1], repo = match[2].replace(/\.git$/, "");
  if (repo === "." || repo === "..") throw new Error("Invalid repository.");
  return { id: `${owner}/${repo}`.toLowerCase(), url: `https://github.com/${owner}/${repo}`, owner, repo };
}

// skill-capabilities/pluginPackage.ts
var hasUnsafePath = (file) => file.includes("\\") || file.startsWith("/") || file.split("/").some((part) => !part || part === "." || part === "..");
function canonicalPluginCapabilityId(pluginId, localId) {
  return `${pluginId}:${localId}`;
}
function resolvePluginCapabilityReference(pluginId, reference) {
  const normalized = normalizeCapabilityId(reference);
  return normalized.startsWith("self:") ? canonicalPluginCapabilityId(pluginId, normalized.slice(5)) : normalized;
}
function validatePluginPackage(input) {
  const manifest = validatePluginManifest(input?.manifest);
  if (!input.files || typeof input.files !== "object" || Array.isArray(input.files)) throw new Error("Missing plugin files.");
  if (Object.keys(input.files).some(hasUnsafePath)) throw new Error("Unsafe plugin path.");
  if (input.files["plugin.json"] !== void 0 && JSON.stringify(validatePluginManifest(JSON.parse(input.files["plugin.json"]))) !== JSON.stringify(manifest)) throw new Error("Plugin manifest and packaged manifest disagree.");
  const expected = /* @__PURE__ */ new Set(["plugin.json"]);
  const capabilities = [];
  const capabilityIds = /* @__PURE__ */ new Set();
  for (const manifestPath of manifest.capabilities) {
    expected.add(manifestPath);
    const directory = manifestPath.slice(0, -"/capability.json".length);
    const raw = input.files[manifestPath];
    if (typeof raw !== "string" || raw.length > 64e3) throw new Error(`Missing or oversized ${manifestPath}.`);
    const capability = validateCapabilityManifest(JSON.parse(raw));
    if (directory.split("/").at(-1) !== capability.id || capabilityIds.has(capability.id)) throw new Error("Capability directory and id must match and be unique.");
    if (capability.version !== manifest.version) throw new Error("Capability versions must match the plugin version.");
    capabilityIds.add(capability.id);
    const entry = `${directory}/${capability.entry}`;
    expected.add(entry);
    const source = input.files[entry];
    if (typeof source !== "string" || !source.trim() || source.length > 256e3) throw new Error(`Missing or oversized ${entry}.`);
    for (const asset of capability.assets ?? []) {
      const file = `${directory}/${asset.path}`;
      expected.add(file);
      const text = input.files[file];
      if (asset.mimeType === "model/gltf-binary" && (typeof text !== "string" || text.length !== Math.ceil(asset.bytes / 3) * 4 || !/^[A-Za-z0-9+/]*={0,2}$/.test(text) || btoa(atob(text)) !== text)) throw new Error(`Noncanonical binary plugin asset: ${file}`);
      if (typeof text !== "string" || (asset.mimeType === "model/gltf-binary" ? atob(text).length : new TextEncoder().encode(text).length) !== asset.bytes) throw new Error(`Missing or oversized plugin asset: ${file}`);
    }
    capabilities.push({ path: manifestPath, manifest: capability, source });
  }
  const skills = [];
  for (const manifestPath of manifest.skills) {
    expected.add(manifestPath);
    const directory = manifestPath.slice(0, -"/skill.json".length);
    const raw = input.files[manifestPath];
    if (typeof raw !== "string" || raw.length > 64e3) throw new Error(`Missing or oversized ${manifestPath}.`);
    const skillManifest = validateManifest(JSON.parse(raw));
    if (directory.split("/").at(-1) !== skillManifest.id) throw new Error("Skill directory and id must match.");
    if (skillManifest.version !== manifest.version) throw new Error("Skill versions must match the plugin version.");
    const files = {};
    for (const relative of ["SKILL.md", ...skillManifest.tools.map((tool) => tool.entry)]) {
      const path = `${directory}/${relative}`;
      expected.add(path);
      if (typeof input.files[path] !== "string") throw new Error(`Missing ${path}.`);
      files[relative] = input.files[path];
    }
    const localCapabilities = skillManifest.capabilities.filter((capability) => normalizeCapabilityId(capability).startsWith("self:"));
    if (localCapabilities.some((capability) => !capabilityIds.has(normalizeCapabilityId(capability).slice(5)))) throw new Error("Skill references a capability not supplied by its plugin.");
    if (skillManifest.capabilities.some((capability) => {
      const normalized = normalizeCapabilityId(capability);
      return !normalized.startsWith("self:") && !NODUS_CAPABILITY_IDS.includes(normalized);
    })) throw new Error("Plugin v1 cannot depend on another plugin.");
    skills.push({ path: manifestPath, package: validateSkillPackage({ manifest: skillManifest, files }) });
  }
  const actual = Object.keys(input.files);
  if (actual.some((file) => !expected.has(file)) || [...expected].some((file) => file !== "plugin.json" && !(file in input.files))) throw new Error("Unexpected or missing plugin file.");
  return { manifest, files: structuredClone(input.files), skills, capabilities };
}
function mergedPluginPermissions(pkg) {
  return {
    network: pkg.capabilities.flatMap((capability) => capability.manifest.permissions.network ?? []),
    secrets: pkg.capabilities.flatMap((capability) => capability.manifest.permissions.secrets ?? []),
    ...pkg.capabilities.some((capability) => capability.manifest.permissions.storage) ? { storage: { maxBytes: pkg.capabilities.reduce((sum, capability) => sum + (capability.manifest.permissions.storage?.maxBytes ?? 0), 0) } } : {}
  };
}
function permissionsExpand(previous, next) {
  const priorNetworks = new Set((previous.network ?? []).flatMap((endpoint) => endpoint.methods.flatMap((method) => endpoint.pathPrefixes.map((path) => `${endpoint.id}|${endpoint.origin}|${method}|${path}`))));
  const nextNetworks = (next.network ?? []).flatMap((endpoint) => endpoint.methods.flatMap((method) => endpoint.pathPrefixes.map((path) => `${endpoint.id}|${endpoint.origin}|${method}|${path}`)));
  if (nextNetworks.some((permission) => !priorNetworks.has(permission))) return true;
  const priorSecrets = new Set((previous.secrets ?? []).map((secret) => `${secret.id}|${secret.endpointId}|${secret.header}|${secret.prefix ?? ""}`));
  if ((next.secrets ?? []).some((secret) => !priorSecrets.has(`${secret.id}|${secret.endpointId}|${secret.header}|${secret.prefix ?? ""}`))) return true;
  return (next.storage?.maxBytes ?? 0) > (previous.storage?.maxBytes ?? 0);
}
export {
  NODUS_CAPABILITY_IDS as BUILTIN_CAPABILITY_IDS,
  CAPABILITY_API_VERSION,
  DEFAULT_SKILL_SOURCE,
  SKILL_CAPABILITIES,
  SUPPORTED_SKILL_CAPABILITIES,
  assertSkillCapabilitiesSupported,
  canonicalPluginCapabilityId,
  compareSemver,
  isCapabilityReference,
  jsonSchemaMatches,
  mergedPluginPermissions,
  normalizeCapabilityId,
  normalizeSkillSource,
  permissionsExpand,
  resolvePluginCapabilityReference,
  skillSlug,
  unsupportedSkillCapabilities,
  validateCapabilityManifest,
  validateManifest,
  validatePackagedModelResult,
  validatePluginAssets,
  validatePluginManifest,
  validatePluginPackage,
  validateSkillPackage
};
