import type { RDKitModule } from '@rdkit/rdkit';
import type { ChemistryRule } from './chemistryDocument';
import { canonicalScene, sceneFromMolfile, sceneMolfile, type ChemicalScene } from './chemistryScene';

export interface MechanismEndpoint { molecule: number; atom?: number; bond?: number }
export interface CheckedMechanism {
  rule: ChemistryRule;
  scope: 'conditional-elementary-rule-not-product-prediction';
  source: string;
  scenes: ChemicalScene[];
  reactants: number[];
  products: number[];
  atomMap: Array<{ from: [number, number]; to: [number, number] }>;
  electronFlow: Array<{ from: MechanismEndpoint; to: MechanismEndpoint }>;
  bondEdits: string[];
  canonicalProducts: string[];
  limitations: string[];
  title?: string;
  geometry?: { description: string; molfile3D: string; dihedralDegrees?: number };
  /** Contributors of one species rather than a transformation; drawn with a double-headed arrow. */
  resonance?: boolean;
}

function inventory(scene: ChemicalScene, kit: RDKitModule): Record<string, number> {
  const m = kit.get_mol(sceneMolfile(scene));
  if (!m) throw new Error('Invalid mechanism stage.');
  try {
    const j = JSON.parse(m.get_json()), result: Record<string, number> = { charge: 0 };
    for (const raw of j.molecules[0].atoms) {
      const a = { ...j.defaults.atom, ...raw }, key = `${a.z}:${a.isotope}`;
      result[key] = (result[key] ?? 0) + 1;
      result['1:0'] = (result['1:0'] ?? 0) + a.impHs;
      result.charge += a.chg;
      if (a.nRad) throw new Error('Radical mechanism stages are unsupported.');
    }
    return result;
  } finally { m.delete(); }
}

export function validateMechanismLedger(mechanism: CheckedMechanism, kit: RDKitModule): void {
  const sum = (indices: number[]) => { const total: Record<string, number> = {}; for (const i of indices) for (const [k, n] of Object.entries(inventory(mechanism.scenes[i], kit))) total[k] = (total[k] ?? 0) + n; return Object.entries(total).filter(([, n]) => n).sort().toString(); };
  if (sum(mechanism.reactants) !== sum(mechanism.products)) throw new Error('Mechanism violates atom/isotope/charge conservation.');
  const left = new Set<string>(), right = new Set<string>();
  for (const mapping of mechanism.atomMap) {
    const a = mechanism.scenes[mapping.from[0]]?.atoms[mapping.from[1]], b = mechanism.scenes[mapping.to[0]]?.atoms[mapping.to[1]];
    if (!mechanism.reactants.includes(mapping.from[0]) || !mechanism.products.includes(mapping.to[0])
      || !a || !b || a.element !== b.element || a.isotope !== b.isotope || left.has(mapping.from.toString()) || right.has(mapping.to.toString())) throw new Error('Mechanism has an invalid atom mapping.');
    left.add(mapping.from.toString()); right.add(mapping.to.toString());
  }
  if (left.size !== mechanism.reactants.reduce((n, i) => n + mechanism.scenes[i].atoms.length, 0)
    || right.size !== mechanism.products.reduce((n, i) => n + mechanism.scenes[i].atoms.length, 0)) throw new Error('Mechanism mapping is incomplete.');
  for (const flow of mechanism.electronFlow) for (const endpoint of [flow.from, flow.to]) {
    const scene = mechanism.scenes[endpoint.molecule];
    if (!mechanism.reactants.includes(endpoint.molecule) || !scene || (endpoint.atom != null) === (endpoint.bond != null) || (endpoint.atom != null ? !scene.atoms[endpoint.atom] : !scene.bonds[endpoint.bond!])) throw new Error('Invalid electron-flow endpoint.');
  }
}

/** A small explicit rule library. Applicability is chemical, never inferred from
 * a balanced ledger alone. Products are generated by graph edits, not by an LLM. */
export function deriveMechanism(rule: CheckedMechanism['rule'], inputs: string[], kit: RDKitModule): CheckedMechanism {
  const read = (source: string) => {
    const m = kit.get_mol(source); if (!m) throw new Error('Invalid mechanism input.');
    try {
      const scene = sceneFromMolfile(m.get_molblock());
      if (canonicalScene(scene, kit) !== m.get_smiles()) throw new Error('Mechanism input layout changed the reference graph.');
      return scene;
    } finally { m.delete(); }
  };
  const initial = inputs.map(read), substrate = initial[0];
  if (!substrate || substrate.atoms.length > 20 || substrate.atoms.some(a => a.charge || a.isotope)) throw new Error('Mechanism substrate is outside the neutral, small-molecule rule scope.');
  let result: CheckedMechanism;
  if (rule === 'sn2') {
    if (inputs.length !== 2 || !['[OH-]', '[I-]'].includes(inputs[1]) || initial[1].atoms.length !== 1) throw new Error('SN2 currently requires hydroxide or iodide as the explicitly supplied nucleophile.');
    const halogens = substrate.atoms.flatMap((a, i) => ['Cl', 'Br', 'I'].includes(a.element) ? [i] : []);
    if (halogens.length !== 1 || substrate.atoms.some(a => !['C', 'H', 'Cl', 'Br', 'I'].includes(a.element)) || substrate.bonds.some(b => b.order !== 1)
      || substrate.bonds.length !== substrate.atoms.length - 1) throw new Error('SN2 supports one saturated acyclic alkyl halide, not aryl/vinyl/bridged or multifunctional substrates.');
    const leaving = halogens[0], leavingBond = substrate.bonds.findIndex(b => b.a === leaving || b.b === leaving);
    const link = substrate.bonds[leavingBond], centre = link.a === leaving ? link.b : link.a;
    const neighbours = substrate.bonds.filter(b => b.a === centre || b.b === centre).map(b => b.a === centre ? b.b : b.a);
    if (substrate.atoms[centre].element !== 'C' || neighbours.filter(a => substrate.atoms[a].element === 'C').length > 2) throw new Error('Tertiary SN2 substrates are outside this rule.');
    if (neighbours.some(a => a !== leaving && substrate.atoms[a].element === 'C' && substrate.bonds.filter(b => b.a === a || b.b === a).length > 3)) throw new Error('Sterically congested beta-branched SN2 substrates require separate assessment.');
    // Rigid rotation keeps stereochemistry, places the leaving group to the
    // right so the incoming left-hand nucleophile is on the backside.
    const origin = substrate.atoms[centre], lg = substrate.atoms[leaving], theta = -Math.atan2(lg.y - origin.y, lg.x - origin.x), ox = origin.x, oy = origin.y;
    substrate.atoms.forEach(a => { const x = a.x - ox, y = a.y - oy; a.x = x * Math.cos(theta) - y * Math.sin(theta); a.y = x * Math.sin(theta) + y * Math.cos(theta); });
    const product = structuredClone(substrate), incoming = initial[1].atoms[0];
    product.atoms[leaving] = { ...product.atoms[leaving], element: incoming.element, label: incoming.element === 'O' ? 'OH' : incoming.element, charge: 0 };
    // Invert geometrical parity at the reacting carbon, NOT its R/S text. CIP
    // priorities are recomputed after changing the ligand identity.
    const probe = kit.get_mol(sceneMolfile(substrate));
    if (!probe) throw new Error('Invalid reacting-carbon geometry.');
    try {
      const tags = JSON.parse(probe.get_stereo_tags()).CIP_atoms as Array<[number, string]>;
      if (tags.some(([i, tag]) => i === centre && tag !== '(?)') && !product.bonds.some(b => b.a === centre && b.stereo)) throw new Error('Reacting-carbon inversion cannot be certified from this layout.');
    } finally { probe.delete(); }
    product.bonds.filter(b => b.a === centre && b.stereo).forEach(b => { b.stereo = b.stereo === 1 ? 6 : 1; });
    const ion: ChemicalScene = { atoms: [{ ...substrate.atoms[leaving], id: 'a0', x: 0, y: 0, charge: -1, label: `${substrate.atoms[leaving].element}^{-}` }], bonds: [] };
    result = { rule, scope: 'conditional-elementary-rule-not-product-prediction', source: 'https://openstax.org/books/organic-chemistry/pages/11-2-the-sn2-reaction', scenes: [initial[1], substrate, product, ion], reactants: [0, 1], products: [2, 3],
      atomMap: [...substrate.atoms.map((_, a) => ({ from: [1, a] as [number, number], to: (a === leaving ? [3, 0] : [2, a]) as [number, number] })), { from: [0, 0], to: [2, leaving] }],
      electronFlow: [{ from: { molecule: 0, atom: 0 }, to: { molecule: 1, atom: centre } }, { from: { molecule: 1, bond: leavingBond }, to: { molecule: 1, atom: leaving } }],
      bondEdits: ['Break C–leaving-group; form C–nucleophile in one concerted step.', 'Nucleophile charge −1→0; leaving-group charge 0→−1; invert reacting-carbon geometry.'], canonicalProducts: [],
      limitations: ['Conditional SN2 mechanism, not a prediction of dominant product, rate or yield. Solvent, temperature and SN2/E2 competition are not determined.', 'No transition-state geometry or experimental conditions are inferred.'] };
  } else if (rule === 'amide-resonance') {
    if (inputs.length !== 1 || substrate.atoms.some(a => !['C', 'H', 'N', 'O'].includes(a.element)) || substrate.bonds.length !== substrate.atoms.length - 1) throw new Error('Amide resonance supports a small acyclic N,N-dimethylamide.');
    const carbonyls = substrate.bonds.map((b, i) => ({ b, i })).filter(({ b }) => b.order === 2 && [substrate.atoms[b.a].element, substrate.atoms[b.b].element].sort().join('') === 'CO');
    if (carbonyls.length !== 1 || substrate.bonds.filter(b => b.order > 1).length !== 1) throw new Error('Exactly one isolated amide carbonyl is required.');
    const { b: co, i: coIndex } = carbonyls[0], carbon = substrate.atoms[co.a].element === 'C' ? co.a : co.b, oxygen = carbon === co.a ? co.b : co.a;
    const cnIndex = substrate.bonds.findIndex(b => (b.a === carbon && substrate.atoms[b.b].element === 'N') || (b.b === carbon && substrate.atoms[b.a].element === 'N'));
    if (cnIndex < 0) throw new Error('The carbonyl is not an amide.');
    const cn = substrate.bonds[cnIndex], nitrogen = cn.a === carbon ? cn.b : cn.a;
    const methyls = substrate.bonds.filter(b => b.a === nitrogen || b.b === nitrogen).map(b => b.a === nitrogen ? b.b : b.a).filter(a => a !== carbon);
    if (methyls.length !== 2 || methyls.some(a => substrate.atoms[a].label !== 'CH_3')) throw new Error('Only N,N-dimethylamide resonance is currently supported.');
    const product = structuredClone(substrate);
    product.bonds[coIndex].order = 1; product.bonds[cnIndex].order = 2;
    product.atoms[oxygen].charge = -1; product.atoms[oxygen].label = 'O^{-}';
    product.atoms[nitrogen].charge = 1; product.atoms[nitrogen].label = 'N^{+}';
    result = { rule, scope: 'conditional-elementary-rule-not-product-prediction', source: 'https://openstax.org/books/organic-chemistry/pages/24-3-basicity-of-amines', scenes: [substrate, product], reactants: [0], products: [1],
      atomMap: substrate.atoms.map((_, a) => ({ from: [0, a], to: [1, a] })),
      electronFlow: [{ from: { molecule: 0, atom: nitrogen }, to: { molecule: 0, bond: cnIndex } }, { from: { molecule: 0, bond: coIndex }, to: { molecule: 0, atom: oxygen } }],
      bondEdits: ['C=O→C–O−; C–N→C=N+; connectivity and all atoms unchanged.'], canonicalProducts: [],
      limitations: ['These are resonance contributors, not distinct intermediates, an equilibrium or a temporal reaction.'] };
  } else throw new Error('Use the bounded extended mechanism engine for this rule.');
  result.canonicalProducts = result.products.map(i => canonicalScene(result.scenes[i], kit));
  validateMechanismLedger(result, kit);
  return result;
}
